app:
  datasource:
    jdbc-url: jdbc:sqlserver://127.0.0.1:1443;user=sa;password=Password123
    pool-size: 30



#docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Password123' -p 1443:1443 -d mcr.microsoft.com/mssql/server:2017-latest
#docker exec -it 2a2dd2833da4 /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Password123